/**
 * Build the field map from a DMMF datamodel and render it as a module.
 *
 * Kept separate from `bin.ts` so the whole of it is testable without spawning
 * a generator process: `bin.ts` is plumbing, this is the behaviour.
 */

import { parseAnnotations } from "../annotations.ts";
import { type ModelInput, resolveModel } from "../declarations.ts";
import { FieldsealConfigurationError } from "../errors.ts";
import { FIELD_MAP_VERSION, type FieldMap } from "../fieldmap.ts";

/** The shape this needs out of `options.dmmf.datamodel`. */
export interface Datamodel {
  readonly models: readonly ModelInput[];
}

/**
 * Resolve every model, reporting *all* problems at once.
 *
 * One model's bad declaration must not hide the next model's: a schema with
 * four mistakes should take one `prisma generate` to find, not four.
 */
export function buildFieldMap(datamodel: Datamodel, generator: string): FieldMap {
  const models = [];
  const problems: string[] = [];
  for (const m of datamodel.models) {
    try {
      const resolved = resolveModel(m, parseAnnotations);
      if (resolved !== null) models.push(resolved);
    } catch (e) {
      problems.push(e instanceof Error ? e.message : String(e));
    }
  }
  if (problems.length > 0) {
    throw new FieldsealConfigurationError(
      `fieldseal: ${String(problems.length)} model(s) have declaration errors.\n\n` +
        problems.join("\n\n"),
    );
  }
  return { version: FIELD_MAP_VERSION, generator, models };
}

/**
 * Render the map as a TypeScript module.
 *
 * TypeScript rather than JSON because Prisma 7's own client generator emits
 * `.ts` -- the consuming project already compiles generated sources, and a
 * typed export means a map that stops matching `FieldMap` fails the build
 * rather than at the first request.
 */
export function renderModule(map: FieldMap, importPath: string): string {
  return `// Generated by ${map.generator}. Do not edit.
//
// Built at \`prisma generate\` from the \`///\` @fieldseal annotations in the
// schema. Prisma 7 does not expose those at runtime -- \`Prisma.dmmf\` is gone
// and the client's runtime data model carries no documentation -- so this file
// is how the declarations reach the extension.
//
// It contains declarations only: no key material, nothing derived, nothing
// secret. Commit it.
//
// Changing a \`column_uuid\` or \`table_uuid\` here does not re-key anything; it
// makes existing rows undecryptable (spec §6.1). Changing an index's \`idf\`,
// \`normalize\` or \`truncate_bits\` after any row is written is a NEW index
// under spec §7.8 and requires a full backfill, not an edit.

import type { FieldMap } from ${JSON.stringify(importPath)};

export const fieldsealFieldMap: FieldMap = ${stable(map)};
`;
}

/**
 * JSON with stable key order, so regenerating an unchanged schema produces a
 * byte-identical file and shows up as no diff.
 */
function stable(value: unknown, indent = 0): string {
  const pad = "  ".repeat(indent + 1);
  const closePad = "  ".repeat(indent);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    return `[\n${value.map((v) => pad + stable(v, indent + 1)).join(",\n")}\n${closePad}]`;
  }
  if (value !== null && typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).filter(
      ([, v]) => v !== undefined,
    );
    if (entries.length === 0) return "{}";
    return `{\n${entries
      .map(([k, v]) => `${pad}${JSON.stringify(k)}: ${stable(v, indent + 1)}`)
      .join(",\n")}\n${closePad}}`;
  }
  return JSON.stringify(value);
}
