"""`nfc-casefold-v1` (docs/09 §7), implemented for the generator alone.

The generator imports neither core (see `tools/vector-gen/README.md`). That
rule matters most here: if the expected index value in a vector came from a
core's normalizer, a bug in that core would be published as the answer every
other implementation is checked against. So this is a third, independent
implementation of the same published algorithms -- UAX #15 canonical
decomposition, ordering and composition, plus CaseFolding.txt statuses C+F --
over the same vendored UCD data (`_ucd_tables.py`, generated by
`tools/ucd-gen/generate.py` from the published files).

Sharing the *data* is not a dependency; the data is the Unicode Character
Database. Sharing an implementation would be.

It is written for obviousness rather than speed: the generator normalizes a
few dozen strings, so a slow, direct transcription of the standard is the
right trade, and it is validated against the official NormalizationTest.txt
by `tests/test_normalizer.py`.
"""

from __future__ import annotations

from ._ucd_tables import (
    UNICODE_VERSION,
    _ASSIGNED,
    _CASEFOLD,
    _CCC,
    _DECOMP,
    _EXCLUSIONS,
)

__all__ = ["UNICODE_VERSION", "normalize_nfc_casefold_v1", "nfc",
           "casefold_full", "first_unassigned", "UnassignedCodePoint",
           "UNINDEXABLE_PREIMAGE"]

# docs/09 §7.2: the reserved preimage behind `on_unindexable = bucket`.
# The leading 0xFF can never appear in UTF-8, so no input this
# normalizer accepts can produce it -- the marker cannot collide with a
# real value by construction rather than by luck.
UNINDEXABLE_PREIMAGE = bytes([0xFF]) + b"fieldseal-unindexable-v1"

S_BASE, L_BASE, V_BASE, T_BASE = 0xAC00, 0x1100, 0x1161, 0x11A7
L_COUNT, V_COUNT, T_COUNT = 19, 21, 28
N_COUNT = V_COUNT * T_COUNT
S_COUNT = L_COUNT * N_COUNT


class UnassignedCodePoint(ValueError):
    """Raised for input the pinned Unicode version does not define."""


def _parse_map(blob: str) -> dict[int, list[int]]:
    out: dict[int, list[int]] = {}
    for entry in blob.split(";"):
        src, _, dst = entry.partition(">")
        out[int(src, 16)] = [int(h, 16) for h in dst.split(",")]
    return out


CASEFOLD = _parse_map(_CASEFOLD)
DECOMP = _parse_map(_DECOMP)
CCC = {int(k, 16): int(v, 16)
       for k, _, v in (e.partition(":") for e in _CCC.split(";"))}
EXCLUSIONS = {int(h, 16) for h in _EXCLUSIONS.split(";") if h}
COMPOSE = {tuple(d): cp for cp, d in DECOMP.items()
           if len(d) == 2 and cp not in EXCLUSIONS}
ASSIGNED = []
for _r in _ASSIGNED.split(";"):
    _a, _, _b = _r.partition("-")
    ASSIGNED.append((int(_a, 16), int(_b, 16) if _b else int(_a, 16)))


def first_unassigned(text: str) -> int | None:
    """The first code point not assigned in the pinned version, or None.

    Linear over the ranges on purpose -- 743 of them, a few dozen strings.
    Surrogates count as unassigned: they have no UTF-8 encoding, so a value
    containing one has no bytes for the index to be derived from.
    """
    for ch in text:
        cp = ord(ch)
        if 0xD800 <= cp <= 0xDFFF:
            return cp
        if not any(lo <= cp <= hi for lo, hi in ASSIGNED):
            return cp
    return None


def casefold_full(text: str) -> str:
    """CaseFolding.txt statuses C and F, per code point."""
    out = []
    for ch in text:
        mapped = CASEFOLD.get(ord(ch))
        out.append(ch if mapped is None else "".join(chr(c) for c in mapped))
    return "".join(out)


def _full_decompose(cp: int) -> list[int]:
    if S_BASE <= cp < S_BASE + S_COUNT:
        i = cp - S_BASE
        out = [L_BASE + i // N_COUNT, V_BASE + (i % N_COUNT) // T_COUNT]
        if i % T_COUNT:
            out.append(T_BASE + i % T_COUNT)
        return out
    d = DECOMP.get(cp)
    if d is None:
        return [cp]
    out = []
    for c in d:
        out.extend(_full_decompose(c))
    return out


def _canonical_order(cps: list[int]) -> list[int]:
    """Bubble adjacent pairs until stable -- the textbook statement of the
    canonical ordering algorithm (UAX #15 D108), not the fastest form."""
    cps = list(cps)
    changed = True
    while changed:
        changed = False
        for i in range(len(cps) - 1):
            a, b = CCC.get(cps[i], 0), CCC.get(cps[i + 1], 0)
            if b and a > b:
                cps[i], cps[i + 1] = cps[i + 1], cps[i]
                changed = True
    return cps


def _canonical_compose(cps: list[int]) -> list[int]:
    if not cps:
        return []
    out = [cps[0]]
    starter = 0 if CCC.get(cps[0], 0) == 0 else None
    last_cc = CCC.get(cps[0], 0)
    for cp in cps[1:]:
        cc = CCC.get(cp, 0)
        if starter is not None and (last_cc == 0 or last_cc < cc):
            base = out[starter]
            composite = None
            if L_BASE <= base < L_BASE + L_COUNT and V_BASE <= cp < V_BASE + V_COUNT:
                composite = S_BASE + ((base - L_BASE) * V_COUNT
                                      + (cp - V_BASE)) * T_COUNT
            elif (S_BASE <= base < S_BASE + S_COUNT
                  and (base - S_BASE) % T_COUNT == 0
                  and T_BASE < cp < T_BASE + T_COUNT):
                composite = base + (cp - T_BASE)
            else:
                composite = COMPOSE.get((base, cp))
            if composite is not None:
                out[starter] = composite
                continue
        out.append(cp)
        if cc == 0:
            starter = len(out) - 1
            last_cc = 0
        else:
            last_cc = cc
    return out


def nfc(text: str) -> str:
    """Normalization Form C at the pinned Unicode version."""
    cps: list[int] = []
    for ch in text:
        cps.extend(_full_decompose(ord(ch)))
    return "".join(chr(c) for c in _canonical_compose(_canonical_order(cps)))


def normalize_nfc_casefold_v1(value: str) -> bytes:
    """docs/09 §7: NFC, full case folding, NFC again, then UTF-8.

    The second NFC is what makes this collide case variants rather than
    merely being deterministic: folding a precomposed character can yield a
    decomposed sequence, so U+0390 and its uppercase spelling U+03AA U+0301
    would otherwise produce two different index values for one letter.
    """
    stray = first_unassigned(value)
    if stray is not None:
        raise UnassignedCodePoint(
            f"U+{stray:04X} is not assigned in Unicode {UNICODE_VERSION}")
    return nfc(casefold_full(nfc(value))).encode("utf-8")
