#!/usr/bin/env python3
"""Tier 2: do the two stacks agree on the *shape* of the table, not just its
identifiers?

    python check_schema_shape.py

`check_declarations.py` compares what the two stacks say about the columns.
This compares what they say about the **schema** -- types, nullability,
indexes -- by asking Prisma what DDL it would emit for its own schema and
diffing that against the database Django's migration actually built.

**`prisma migrate diff` against the live database does not work as a gate,
and the obvious form of it is a trap.** Pointed at the real database, Prisma
sees `django_migrations`, which it does not declare, and reports a permanent
diff. Declaring that table in the Prisma schema introduces a *second*
permanent diff: Django 4.1+ emits `bigint GENERATED BY DEFAULT AS IDENTITY`
where Prisma's `@default(autoincrement())` emits a sequence. So the diff is
taken `--from-empty`, materialized into a scratch schema, and compared
column by column -- which is a comparison this demo controls the terms of.

The scratch schema is created and dropped by this script. It touches nothing
in `public`.

**Prisma 7.10 spells the flag `--to-schema`.** `--to-schema-datamodel` was
removed and the CLI says so; the older spelling appears in a lot of writing
about earlier versions.
"""

from __future__ import annotations

import os
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
PRISMA_DIR = HERE / "prisma"

SCRATCH = "prisma_expected"
LIVE = "public"

#: Tables in the live schema that Prisma is not expected to declare.
#:
#: Exactly one, and it is Django's own migration bookkeeping. Keeping the
#: demo's `INSTALLED_APPS` free of `contenttypes` and `auth` is what keeps
#: this list one line long -- those would add four more tables, and a list
#: with five entries stops being a fact and starts being a filter.
DJANGO_OWNED = {"django_migrations"}

#: What is compared, per column. `character_maximum_length` and
#: `numeric_precision` are NULL on every column in this model by design --
#: §2.2's omissions (TextField/String, no `unique`, a uuid pk with no
#: database default) exist so that the comparison has no cell where two
#: reasonable tools would legitimately differ.
COLUMN_ATTRS = (
    "data_type",
    "is_nullable",
    "character_maximum_length",
    "numeric_precision",
)


def _fail(message: str) -> None:
    sys.stdout.flush()
    print(f"\ncheck_schema_shape: FAILED\n\n{message}", file=sys.stderr)
    raise SystemExit(1)


def prisma_ddl() -> str:
    """The DDL Prisma would emit for its schema, from an empty database."""
    npx = "npx.cmd" if os.name == "nt" else "npx"
    proc = subprocess.run(
        [npx, "prisma", "migrate", "diff", "--from-empty", "--to-schema",
         "schema.prisma", "--script"],
        cwd=PRISMA_DIR,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        _fail("`prisma migrate diff` failed:\n\n"
              + (proc.stderr.strip() or "(no output)"))
    return proc.stdout


def columns(cur: object, schema: str) -> dict[tuple[str, str], tuple]:
    rows = cur.execute(  # type: ignore[attr-defined]
        "SELECT table_name, column_name, " + ", ".join(COLUMN_ATTRS) + " "
        "FROM information_schema.columns WHERE table_schema = %s "
        "ORDER BY table_name, column_name",
        (schema,),
    ).fetchall()
    return {(r[0], r[1]): tuple(r[2:]) for r in rows}


def indexes(cur: object, schema: str) -> dict[tuple[str, str], str]:
    rows = cur.execute(  # type: ignore[attr-defined]
        "SELECT tablename, indexname, indexdef FROM pg_indexes "
        "WHERE schemaname = %s ORDER BY tablename, indexname",
        (schema,),
    ).fetchall()
    # The schema qualifier is the one thing that must differ, so it is the one
    # thing normalized away.
    return {(r[0], r[1]): r[2].replace(f"{schema}.", "") for r in rows}


def main() -> int:
    import psycopg

    url = os.environ.get(
        "DATABASE_URL", "postgresql://postgres:postgres@localhost:5432/fieldseal_demo"
    )
    ddl = prisma_ddl()

    print("fieldseal patient-directory demo -- schema shape check")
    print()
    print("  Prisma  `prisma migrate diff --from-empty --to-schema "
          "schema.prisma`,")
    print(f"          materialized into the scratch schema \"{SCRATCH}\"")
    print(f"  Django  the \"{LIVE}\" schema, as `manage.py migrate` built it")
    print()

    problems: list[str] = []
    with psycopg.connect(url, autocommit=True) as conn:
        with conn.cursor() as cur:
            cur.execute(f'DROP SCHEMA IF EXISTS "{SCRATCH}" CASCADE')
            cur.execute(f'CREATE SCHEMA "{SCRATCH}"')
        try:
            with conn.cursor() as cur:
                cur.execute(f'SET search_path TO "{SCRATCH}"')
                # The script opens with `CREATE SCHEMA IF NOT EXISTS
                # "public"`, which is a no-op here: every CREATE TABLE in it
                # is unqualified, so it lands in the search_path schema.
                cur.execute(ddl)
                cur.execute("SET search_path TO public")

                want, have = columns(cur, SCRATCH), columns(cur, LIVE)
                want_idx, have_idx = indexes(cur, SCRATCH), indexes(cur, LIVE)
        finally:
            with conn.cursor() as cur:
                cur.execute(f'DROP SCHEMA IF EXISTS "{SCRATCH}" CASCADE')

    declared_tables = {t for t, _ in want}
    live_tables = {t for t, _ in have}

    for table in sorted(declared_tables - live_tables):
        problems.append(
            f'table "{table}": Prisma declares it and the database does not '
            f"have it. Django owns the DDL here, so this means the migration "
            f"and the Prisma schema have drifted apart -- run "
            f"`manage.py makemigrations`."
        )
    for table in sorted(live_tables - declared_tables - DJANGO_OWNED):
        problems.append(
            f'table "{table}": the database has it and Prisma does not '
            f"declare it, so the Prisma stack cannot see it at all. If it is "
            f"Django bookkeeping, add it to DJANGO_OWNED with a reason."
        )

    for key in sorted(set(want) & set(have)):
        if want[key] != have[key]:
            table, column = key
            differing = [
                f"{attr}: Prisma {w!r}, database {h!r}"
                for attr, w, h in zip(COLUMN_ATTRS, want[key], have[key],
                                      strict=True)
                if w != h
            ]
            problems.append(
                f'"{table}"."{column}": ' + "; ".join(differing)
                + ". The two stacks would read and write the same physical "
                "column under different assumptions about it."
            )
    for key in sorted(set(want) - set(have)):
        problems.append(
            f'"{key[0]}"."{key[1]}": declared by Prisma, absent from the '
            f"database. Prisma would fail on first use of the column."
        )
    for key in sorted(set(have) - set(want)):
        if key[0] in DJANGO_OWNED:
            continue
        problems.append(
            f'"{key[0]}"."{key[1]}": in the database, not declared by Prisma. '
            f"Prisma reads and writes rows in this table without it, so a NOT "
            f"NULL column here would fail every Prisma insert."
        )

    for key in sorted(set(want_idx) | set(have_idx)):
        if key[0] in DJANGO_OWNED:
            continue
        w, h = want_idx.get(key), have_idx.get(key)
        if w != h:
            problems.append(
                f'index "{key[1]}" on "{key[0]}": Prisma {w!r}, database '
                f"{h!r}. A blind-index column without its index is a "
                f"sequential scan on every lookup; a missing one on the "
                f"Prisma side means only one stack is paying for it."
            )

    for table in sorted(declared_tables & live_tables):
        cols = sorted(c for t, c in want if t == table)
        idx = sorted(n for t, n in want_idx if t == table)
        print(f'  "{table}"  {len(cols)} columns, {len(idx)} indexes')
        for column in cols:
            attrs = dict(zip(COLUMN_ATTRS, want[(table, column)],
                             strict=True))
            null = "NULL" if attrs["is_nullable"] == "YES" else "NOT NULL"
            print(f'      "{column}"  {attrs["data_type"]}  {null}')
        for name in idx:
            print(f"      index {name}")
    print()

    if problems:
        _fail("\n\n".join(f"- {p}" for p in problems))

    extra = sorted(live_tables - declared_tables)
    print(f"  Both stacks agree on {len(declared_tables & live_tables)} "
          f"table(s), {len(want)} column(s) and {len(want_idx)} index(es).")
    if extra:
        print(f"  Not declared by Prisma, and expected: "
              f"{', '.join(extra)} (Django's own bookkeeping).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
